pages = [{"l":"index.html#","e":false,"i":"","n":"Eunomia","t":"Eunomia","d":"","k":"static","x":""},
{"l":"com/alecdorrington/eunomia.html#","e":false,"i":"","n":"com.alecdorrington.eunomia","t":"com.alecdorrington.eunomia","d":"","k":"package","x":""},
{"l":"com/alecdorrington/eunomia/api.html#","e":false,"i":"","n":"com.alecdorrington.eunomia.api","t":"com.alecdorrington.eunomia.api","d":"","k":"package","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#","e":false,"i":"","n":"ListApi","t":"ListApi","d":"com.alecdorrington.eunomia.api","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#filter-0","e":false,"i":"","n":"filter","t":"filter: Query[Filter]","d":"com.alecdorrington.eunomia.api.ListApi","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#input-0","e":false,"i":"","n":"input","t":"input: EndpointInput[ListQuery]","d":"com.alecdorrington.eunomia.api.ListApi","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#page-0","e":false,"i":"","n":"page","t":"page: EndpointInput[Option[Page]]","d":"com.alecdorrington.eunomia.api.ListApi","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#params-fffff923","e":false,"i":"","n":"params","t":"params(query: ListQuery): List[(String, String)]","d":"com.alecdorrington.eunomia.api.ListApi","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#reply-ffffff67","e":false,"i":"","n":"reply","t":"reply[X : Encoder : Decoder : Schema]: Body[String, ListReply[X]]","d":"com.alecdorrington.eunomia.api.ListApi","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/api/ListApi$.html#sort-0","e":false,"i":"","n":"sort","t":"sort: Query[List[Order]]","d":"com.alecdorrington.eunomia.api.ListApi","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model.html#","e":false,"i":"","n":"com.alecdorrington.eunomia.model","t":"com.alecdorrington.eunomia.model","d":"","k":"package","x":""},
{"l":"com/alecdorrington/eunomia/model/CellFilter$.html#","e":false,"i":"","n":"CellFilter","t":"CellFilter","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/CellFilter$.html#parse-fffff67a","e":false,"i":"","n":"parse","t":"parse(field: String, kind: Kind, input: String): Either[String, Filter]","d":"com.alecdorrington.eunomia.model.CellFilter","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison$.html#","e":false,"i":"","n":"Comparison","t":"Comparison","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison$.html#bySymbolLength-0","e":false,"i":"","n":"bySymbolLength","t":"bySymbolLength: List[Comparison]","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison$.html#fromSymbol-fffffd22","e":false,"i":"","n":"fromSymbol","t":"fromSymbol(symbol: String): Option[Comparison]","d":"com.alecdorrington.eunomia.model.Comparison","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison$.html#given_Decoder_Comparison-0","e":false,"i":"","n":"given_Decoder_Comparison","t":"given_Decoder_Comparison: Decoder[Comparison]","d":"com.alecdorrington.eunomia.model.Comparison","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison$.html#given_Encoder_Comparison-0","e":false,"i":"","n":"given_Encoder_Comparison","t":"given_Encoder_Comparison: Encoder[Comparison]","d":"com.alecdorrington.eunomia.model.Comparison","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#","e":false,"i":"","n":"Comparison","t":"Comparison(val symbol: String)","d":"com.alecdorrington.eunomia.model","k":"enum","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#Eq-0","e":false,"i":"","n":"Eq","t":"Eq extends Comparison","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#Ne-0","e":false,"i":"","n":"Ne","t":"Ne extends Comparison","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#Lt-0","e":false,"i":"","n":"Lt","t":"Lt extends Comparison","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#Le-0","e":false,"i":"","n":"Le","t":"Le extends Comparison","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#Gt-0","e":false,"i":"","n":"Gt","t":"Gt extends Comparison","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Comparison.html#Ge-0","e":false,"i":"","n":"Ge","t":"Ge extends Comparison","d":"com.alecdorrington.eunomia.model.Comparison","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#","e":false,"i":"","n":"Field","t":"Field[-X, B](val name: String, read: X => Option[B])(using B: Scalar[B])","d":"com.alecdorrington.eunomia.model","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#<-fffffa20","e":false,"i":"","n":"<","t":"<(bound: B): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#<=-fffffa20","e":false,"i":"","n":"<=","t":"<=(bound: B): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#>-fffffa20","e":false,"i":"","n":">","t":">(bound: B): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#>=-fffffa20","e":false,"i":"","n":">=","t":">=(bound: B): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#ascending-0","e":false,"i":"","n":"ascending","t":"ascending: Order","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#contains-fffff4e0","e":false,"i":"","n":"contains","t":"contains(text: String)(using B =:= String): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#descending-0","e":false,"i":"","n":"descending","t":"descending: Order","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#is-fffffa20","e":false,"i":"","n":"is","t":"is(value: B): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#isNot-fffffa20","e":false,"i":"","n":"isNot","t":"isNot(value: B): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#kind-0","e":false,"i":"","n":"kind","t":"kind: Kind","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#missing-0","e":false,"i":"","n":"missing","t":"missing: Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"com.alecdorrington.eunomia.model.Field","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#oneOf-fffffe88","e":false,"i":"","n":"oneOf","t":"oneOf(values: B*): Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#present-0","e":false,"i":"","n":"present","t":"present: Filter","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field.html#valueOf-fffffb50","e":false,"i":"","n":"valueOf","t":"valueOf(item: X): Option[Value]","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field$.html#","e":false,"i":"","n":"Field","t":"Field","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Field$.html#of-fffff441","e":false,"i":"","n":"of","t":"of[X]: Builder[X]","d":"com.alecdorrington.eunomia.model.Field","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Field$$Builder.html#","e":false,"i":"","n":"Builder","t":"Builder[X]","d":"com.alecdorrington.eunomia.model.Field","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Field$$Builder.html#apply-fffff324","e":false,"i":"","n":"apply","t":"apply[V, B](name: String, get: X => V)(using nullable: Nullable[V, B], scalar: Scalar[B]): Field[X, B]","d":"com.alecdorrington.eunomia.model.Field.Builder","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter.html#","e":false,"i":"","n":"Filter","t":"Filter","d":"com.alecdorrington.eunomia.model","k":"enum","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Not.html#","e":false,"i":"","n":"Not","t":"Not(filter: Filter)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$And.html#","e":false,"i":"","n":"And","t":"And(filters: List[Filter])","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Or.html#","e":false,"i":"","n":"Or","t":"Or(filters: List[Filter])","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Compare.html#","e":false,"i":"","n":"Compare","t":"Compare(field: String, comparison: Comparison, value: Value)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Contains.html#","e":false,"i":"","n":"Contains","t":"Contains(field: String, text: String)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$OneOf.html#","e":false,"i":"","n":"OneOf","t":"OneOf(field: String, values: List[Value])","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Missing.html#","e":false,"i":"","n":"Missing","t":"Missing(field: String)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Not.html#","e":false,"i":"","n":"Not","t":"Not(filter: Filter)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$And.html#","e":false,"i":"","n":"And","t":"And(filters: List[Filter])","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Or.html#","e":false,"i":"","n":"Or","t":"Or(filters: List[Filter])","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Compare.html#","e":false,"i":"","n":"Compare","t":"Compare(field: String, comparison: Comparison, value: Value)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Contains.html#","e":false,"i":"","n":"Contains","t":"Contains(field: String, text: String)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$OneOf.html#","e":false,"i":"","n":"OneOf","t":"OneOf(field: String, values: List[Value])","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$$Missing.html#","e":false,"i":"","n":"Missing","t":"Missing(field: String)","d":"com.alecdorrington.eunomia.model.Filter","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#","e":false,"i":"","n":"Filter","t":"Filter","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#all-fffff899","e":false,"i":"","n":"all","t":"all(filters: Iterable[Filter]): Filter","d":"com.alecdorrington.eunomia.model.Filter","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#always-0","e":false,"i":"","n":"always","t":"always: Filter","d":"com.alecdorrington.eunomia.model.Filter","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#any-fffff899","e":false,"i":"","n":"any","t":"any(filters: Iterable[Filter]): Filter","d":"com.alecdorrington.eunomia.model.Filter","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#given_Decoder_Filter-0","e":false,"i":"","n":"given_Decoder_Filter","t":"given_Decoder_Filter: Decoder[Filter]","d":"com.alecdorrington.eunomia.model.Filter","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#given_Encoder_Filter-0","e":false,"i":"","n":"given_Encoder_Filter","t":"given_Encoder_Filter: Encoder[Filter]","d":"com.alecdorrington.eunomia.model.Filter","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Filter$.html#never-0","e":false,"i":"","n":"never","t":"never: Filter","d":"com.alecdorrington.eunomia.model.Filter","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Kind.html#","e":false,"i":"","n":"Kind","t":"Kind(val noun: String)","d":"com.alecdorrington.eunomia.model","k":"enum","x":""},
{"l":"com/alecdorrington/eunomia/model/Kind.html#Text-0","e":false,"i":"","n":"Text","t":"Text extends Kind","d":"com.alecdorrington.eunomia.model.Kind","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Kind.html#Whole-0","e":false,"i":"","n":"Whole","t":"Whole extends Kind","d":"com.alecdorrington.eunomia.model.Kind","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Kind.html#Real-0","e":false,"i":"","n":"Real","t":"Real extends Kind","d":"com.alecdorrington.eunomia.model.Kind","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Kind.html#Flag-0","e":false,"i":"","n":"Flag","t":"Flag extends Kind","d":"com.alecdorrington.eunomia.model.Kind","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery.html#","e":false,"i":"","n":"ListQuery","t":"ListQuery(filter: Filter = ..., order: List[Order] = ..., page: Option[Page] = ...)","d":"com.alecdorrington.eunomia.model","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery.html#checked-fffffd81","e":false,"i":"","n":"checked","t":"checked(kinds: Map[String, Kind]): Either[String, ListQuery]","d":"com.alecdorrington.eunomia.model.ListQuery","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery.html#limited-fffff7b6","e":false,"i":"","n":"limited","t":"limited(max: Int): ListQuery","d":"com.alecdorrington.eunomia.model.ListQuery","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery.html#paged-fffff9b9","e":false,"i":"","n":"paged","t":"paged(window: Page): ListQuery","d":"com.alecdorrington.eunomia.model.ListQuery","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery.html#sortedBy-fffffdba","e":false,"i":"","n":"sortedBy","t":"sortedBy(keys: Order*): ListQuery","d":"com.alecdorrington.eunomia.model.ListQuery","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery.html#where-fffff4a2","e":false,"i":"","n":"where","t":"where(narrower: Filter): ListQuery","d":"com.alecdorrington.eunomia.model.ListQuery","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/ListQuery$.html#","e":false,"i":"","n":"ListQuery","t":"ListQuery","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply.html#","e":false,"i":"","n":"ListReply","t":"ListReply[X]","d":"com.alecdorrington.eunomia.model","k":"enum","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$$Window.html#","e":false,"i":"","n":"Window","t":"Window[X](paged: Paged[X])","d":"com.alecdorrington.eunomia.model.ListReply","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$$Whole.html#","e":false,"i":"","n":"Whole","t":"Whole[X](items: List[X])","d":"com.alecdorrington.eunomia.model.ListReply","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$$Window.html#","e":false,"i":"","n":"Window","t":"Window[X](paged: Paged[X])","d":"com.alecdorrington.eunomia.model.ListReply","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$$Whole.html#","e":false,"i":"","n":"Whole","t":"Whole[X](items: List[X])","d":"com.alecdorrington.eunomia.model.ListReply","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$.html#","e":false,"i":"","n":"ListReply","t":"ListReply","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$.html#given_Decoder_ListReply-ffffff69","e":false,"i":"","n":"given_Decoder_ListReply","t":"given_Decoder_ListReply: [X : Decoder] => Decoder[ListReply[X]]","d":"com.alecdorrington.eunomia.model.ListReply","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/ListReply$.html#given_Encoder_ListReply-fffff119","e":false,"i":"","n":"given_Encoder_ListReply","t":"given_Encoder_ListReply: [X : Encoder] => Encoder[ListReply[X]]","d":"com.alecdorrington.eunomia.model.ListReply","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Nullable$.html#","e":false,"i":"","n":"Nullable","t":"Nullable","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Nullable$.html#absent-ec6","e":false,"i":"","n":"absent","t":"absent: [B : Scalar] => Nullable[Option[B], B]","d":"com.alecdorrington.eunomia.model.Nullable","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Nullable$.html#present-ec6","e":false,"i":"","n":"present","t":"present: [B : Scalar] => Nullable[B, B]","d":"com.alecdorrington.eunomia.model.Nullable","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Nullable.html#","e":false,"i":"","n":"Nullable","t":"Nullable[V, B]","d":"com.alecdorrington.eunomia.model","k":"trait","x":""},
{"l":"com/alecdorrington/eunomia/model/Nullable.html#apply-fffffb50","e":false,"i":"","n":"apply","t":"apply(value: V): Option[B]","d":"com.alecdorrington.eunomia.model.Nullable","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Order$.html#","e":false,"i":"","n":"Order","t":"Order","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Order$.html#derived$AsObject-0","e":false,"i":"","n":"derived$AsObject","t":"derived$AsObject: AsObject[Order]","d":"com.alecdorrington.eunomia.model.Order","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Order$.html#parse-2f8","e":false,"i":"","n":"parse","t":"parse(text: String): Order","d":"com.alecdorrington.eunomia.model.Order","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Order$.html#parseAll-94d","e":false,"i":"","n":"parseAll","t":"parseAll(text: String): List[Order]","d":"com.alecdorrington.eunomia.model.Order","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Order$.html#textOf-fffffeb7","e":false,"i":"","n":"textOf","t":"textOf(orders: List[Order]): String","d":"com.alecdorrington.eunomia.model.Order","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Order$.html#toggled-fffff6bb","e":false,"i":"","n":"toggled","t":"toggled(keys: List[Order], field: String): List[Order]","d":"com.alecdorrington.eunomia.model.Order","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Order.html#","e":false,"i":"","n":"Order","t":"Order(field: String, descending: Boolean = ...)","d":"com.alecdorrington.eunomia.model","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Order.html#reversed-0","e":false,"i":"","n":"reversed","t":"reversed: Order","d":"com.alecdorrington.eunomia.model.Order","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Order.html#text-0","e":false,"i":"","n":"text","t":"text: String","d":"com.alecdorrington.eunomia.model.Order","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Page$.html#","e":false,"i":"","n":"Page","t":"Page","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Page$.html#derived$AsObject-0","e":false,"i":"","n":"derived$AsObject","t":"derived$AsObject: AsObject[Page]","d":"com.alecdorrington.eunomia.model.Page","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Page$.html#first-223","e":false,"i":"","n":"first","t":"first(limit: Int): Page","d":"com.alecdorrington.eunomia.model.Page","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Page.html#","e":false,"i":"","n":"Page","t":"Page(offset: Int, limit: Int)","d":"com.alecdorrington.eunomia.model","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Page.html#capped-223","e":false,"i":"","n":"capped","t":"capped(max: Int): Page","d":"com.alecdorrington.eunomia.model.Page","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Page.html#next-0","e":false,"i":"","n":"next","t":"next: Page","d":"com.alecdorrington.eunomia.model.Page","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Page.html#previous-0","e":false,"i":"","n":"previous","t":"previous: Page","d":"com.alecdorrington.eunomia.model.Page","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Page.html#slice-fffff631","e":false,"i":"","n":"slice","t":"slice[X](items: List[X]): List[X]","d":"com.alecdorrington.eunomia.model.Page","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Page.html#valid-0","e":false,"i":"","n":"valid","t":"valid: Boolean","d":"com.alecdorrington.eunomia.model.Page","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged.html#","e":false,"i":"","n":"Paged","t":"Paged[X](items: List[X], total: Int)","d":"com.alecdorrington.eunomia.model","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged.html#map-4fa","e":false,"i":"","n":"map","t":"map[Y](transform: X => Y): Paged[Y]","d":"com.alecdorrington.eunomia.model.Paged","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged$.html#","e":false,"i":"","n":"Paged","t":"Paged","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged$.html#empty-fffffc2b","e":false,"i":"","n":"empty","t":"empty[X]: Paged[X]","d":"com.alecdorrington.eunomia.model.Paged","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged$.html#given_Decoder_Paged-ffffff69","e":false,"i":"","n":"given_Decoder_Paged","t":"given_Decoder_Paged: [X : Decoder] => Decoder[Paged[X]]","d":"com.alecdorrington.eunomia.model.Paged","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged$.html#given_Encoder_Paged-fffff119","e":false,"i":"","n":"given_Encoder_Paged","t":"given_Encoder_Paged: [X : Encoder] => Encoder[Paged[X]]","d":"com.alecdorrington.eunomia.model.Paged","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Paged$.html#whole-5fb","e":false,"i":"","n":"whole","t":"whole[X](items: List[X]): Paged[X]","d":"com.alecdorrington.eunomia.model.Paged","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#","e":false,"i":"","n":"Scalar","t":"Scalar","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#apply-fffff7b4","e":false,"i":"","n":"apply","t":"apply[B](of: Kind, read: B => Value): Scalar[B]","d":"com.alecdorrington.eunomia.model.Scalar","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#given_Scalar_Boolean-0","e":false,"i":"","n":"given_Scalar_Boolean","t":"given_Scalar_Boolean: Scalar[Boolean]","d":"com.alecdorrington.eunomia.model.Scalar","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#given_Scalar_Double-0","e":false,"i":"","n":"given_Scalar_Double","t":"given_Scalar_Double: Scalar[Double]","d":"com.alecdorrington.eunomia.model.Scalar","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#given_Scalar_Int-0","e":false,"i":"","n":"given_Scalar_Int","t":"given_Scalar_Int: Scalar[Int]","d":"com.alecdorrington.eunomia.model.Scalar","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#given_Scalar_Long-0","e":false,"i":"","n":"given_Scalar_Long","t":"given_Scalar_Long: Scalar[Long]","d":"com.alecdorrington.eunomia.model.Scalar","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar$.html#given_Scalar_String-0","e":false,"i":"","n":"given_Scalar_String","t":"given_Scalar_String: Scalar[String]","d":"com.alecdorrington.eunomia.model.Scalar","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar.html#","e":false,"i":"","n":"Scalar","t":"Scalar[B]","d":"com.alecdorrington.eunomia.model","k":"trait","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar.html#by-347","e":false,"i":"","n":"by","t":"by[A](convert: A => B): Scalar[A]","d":"com.alecdorrington.eunomia.model.Scalar","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar.html#encode-dc9","e":false,"i":"","n":"encode","t":"encode(value: B): Value","d":"com.alecdorrington.eunomia.model.Scalar","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Scalar.html#kind-0","e":false,"i":"","n":"kind","t":"kind: Kind","d":"com.alecdorrington.eunomia.model.Scalar","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema$.html#","e":false,"i":"","n":"Schema","t":"Schema","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema$.html#apply-fffff720","e":false,"i":"","n":"apply","t":"apply[X](fields: Field[X, _]*): Schema[X]","d":"com.alecdorrington.eunomia.model.Schema","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema.html#","e":false,"i":"","n":"Schema","t":"Schema[X](val fields: List[Field[X, _]])","d":"com.alecdorrington.eunomia.model","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema.html#fields-0","e":false,"i":"","n":"fields","t":"fields: List[Field[X, _]]","d":"com.alecdorrington.eunomia.model.Schema","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema.html#kinds-0","e":false,"i":"","n":"kinds","t":"kinds: Map[String, Kind]","d":"com.alecdorrington.eunomia.model.Schema","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema.html#matches-fffffe7a","e":false,"i":"","n":"matches","t":"matches(filter: Filter)(item: X): Boolean","d":"com.alecdorrington.eunomia.model.Schema","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema.html#ordering-fffffde0","e":false,"i":"","n":"ordering","t":"ordering(keys: List[Order]): Ordering[X]","d":"com.alecdorrington.eunomia.model.Schema","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Schema.html#run-fffffce6","e":false,"i":"","n":"run","t":"run(query: ListQuery, items: List[X]): Either[String, Paged[X]]","d":"com.alecdorrington.eunomia.model.Schema","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/model/Value.html#","e":false,"i":"","n":"Value","t":"Value","d":"com.alecdorrington.eunomia.model","k":"enum","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Text.html#","e":false,"i":"","n":"Text","t":"Text(text: String)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Whole.html#","e":false,"i":"","n":"Whole","t":"Whole(number: Long)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Real.html#","e":false,"i":"","n":"Real","t":"Real(number: Double)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Flag.html#","e":false,"i":"","n":"Flag","t":"Flag(flag: Boolean)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Text.html#","e":false,"i":"","n":"Text","t":"Text(text: String)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Whole.html#","e":false,"i":"","n":"Whole","t":"Whole(number: Long)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Real.html#","e":false,"i":"","n":"Real","t":"Real(number: Double)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$$Flag.html#","e":false,"i":"","n":"Flag","t":"Flag(flag: Boolean)","d":"com.alecdorrington.eunomia.model.Value","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$.html#","e":false,"i":"","n":"Value","t":"Value","d":"com.alecdorrington.eunomia.model","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$.html#given_Decoder_Value-0","e":false,"i":"","n":"given_Decoder_Value","t":"given_Decoder_Value: Decoder[Value]","d":"com.alecdorrington.eunomia.model.Value","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$.html#given_Encoder_Value-0","e":false,"i":"","n":"given_Encoder_Value","t":"given_Encoder_Value: Encoder[Value]","d":"com.alecdorrington.eunomia.model.Value","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/model/Value$.html#given_Ordering_Value-0","e":false,"i":"","n":"given_Ordering_Value","t":"given_Ordering_Value: Ordering[Value]","d":"com.alecdorrington.eunomia.model.Value","k":"given","x":""},
{"l":"com/alecdorrington/eunomia/server.html#","e":false,"i":"","n":"com.alecdorrington.eunomia.server","t":"com.alecdorrington.eunomia.server","d":"","k":"package","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$.html#","e":false,"i":"","n":"SqlLists","t":"SqlLists","d":"com.alecdorrington.eunomia.server","k":"object","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#","e":false,"i":"","n":"SqlLists","t":"SqlLists(val profile: JdbcProfile, wholeUpTo: Int = ..., maxWindow: Int = ...)","d":"com.alecdorrington.eunomia.server","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#answer-fffff423","e":false,"i":"","n":"answer","t":"answer[E, U](rows: Query[E, U, Seq], columns: Columns[E], query: ListQuery): Either[String, DBIO[ListReply[U]]]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#columns-ffffff21","e":false,"i":"","n":"columns","t":"columns[E](schema: Schema[_])(stored: Column[E]*): Columns[E]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#flag-1cd","e":false,"i":"","n":"flag","t":"flag[E](name: String)(rep: E => Rep[Option[Boolean]]): Column[E]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#profile-0","e":false,"i":"","n":"profile","t":"profile: JdbcProfile","d":"com.alecdorrington.eunomia.server.SqlLists","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#real-1cd","e":false,"i":"","n":"real","t":"real[E](name: String)(rep: E => Rep[Option[Double]]): Column[E]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#text-1cd","e":false,"i":"","n":"text","t":"text[E](name: String)(rep: E => Rep[Option[String]]): Column[E]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists.html#whole-1cd","e":false,"i":"","n":"whole","t":"whole[E](name: String)(rep: E => Rep[Option[Long]]): Column[E]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#","e":false,"i":"","n":"Column","t":"Column[-E](val name: String, val kind: Kind)","d":"com.alecdorrington.eunomia.server.SqlLists","k":"class","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#compare-fffff1f6","e":false,"i":"","n":"compare","t":"compare(row: E, comparison: Comparison, value: Value): Rep[Boolean]","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#contains-587","e":false,"i":"","n":"contains","t":"contains(row: E, text: String): Rep[Boolean]","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#kind-0","e":false,"i":"","n":"kind","t":"kind: Kind","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#missing-ffffff22","e":false,"i":"","n":"missing","t":"missing(row: E): Rep[Boolean]","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"val","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#oneOf-fffffdee","e":false,"i":"","n":"oneOf","t":"oneOf(row: E, values: List[Value]): Rep[Boolean]","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Column.html#ordered-e8c","e":false,"i":"","n":"ordered","t":"ordered(row: E, descending: Boolean): Ordered","d":"com.alecdorrington.eunomia.server.SqlLists.Column","k":"def","x":""},
{"l":"com/alecdorrington/eunomia/server/SqlLists$Columns.html#","e":false,"i":"","n":"Columns","t":"Columns[E]","d":"com.alecdorrington.eunomia.server.SqlLists","k":"class","x":""}];